defmodule Pulso.PromQL.ConformanceTest do
  use ExUnit.Case, async: false

  alias Pulso.PromQL.Evaluator
  alias Pulso.Record.MetricSample
  alias Pulso.Storage.Memory

  @tag skip: is_nil(System.get_env("PULSO_PROMTOOL"))
  test "Prometheus validates results generated by the actual Pulso evaluator" do
    Memory.reset()

    series = [
      {"counter", %{"job" => "api"}, [100, 110, 120, 5, 15, 25, 35]},
      {"gauge", %{"job" => "api"}, [1, 5, 3, 7, 2, 9, 4]},
      {"gauge", %{"job" => "web"}, [2, 4, 6, 8, 10, 12, 14]},
      {"missing", %{}, [1, 2, 3, 4, 5, 6, 7]}
    ]

    records =
      for {name, labels, values} <- series,
          {value, index} <- Enum.with_index(values),
          do: %MetricSample{
            timestamp_ns: index * 10_000_000_000,
            value: value * 1.0,
            labels: Map.put(labels, "__name__", name)
          }

    :ok = Memory.append(:metrics, "reference", records, [])

    expressions =
      [
        "counter",
        "gauge offset 10s",
        "rate(counter[30s])",
        "increase(counter[45s])",
        "irate(counter[1m])",
        "delta(gauge[30s])",
        "sum by(job)(rate(counter[30s]))",
        "avg without(job)(gauge)",
        "sum(gauge)",
        "count(gauge)",
        "min(gauge)",
        "max(gauge)",
        ~s(missing{job=~".*"}),
        ~s(missing{job!~".*"})
      ] ++
        Enum.map(~w(sum avg min max count), &"#{&1}_over_time(gauge[30s])")

    cases =
      for expression <- expressions, time <- [0, 10, 20, 30, 45, 60, 330] do
        assert {:ok, result} = Evaluator.query(expression, "reference", %{end_ts_ns: time * 1_000_000_000})

        reference_case(expression, time, result["data"]["result"])
      end

    range_cases =
      Enum.flat_map(
        ["gauge", "rate(counter[30s])", "sum(gauge)", "gauge offset 10s", ~s(missing{job!~".*"})],
        fn expression ->
          assert {:ok, result} =
                   Evaluator.query(expression, "reference", %{
                     start_ts_ns: 0,
                     end_ts_ns: 60_000_000_000,
                     step_ns: 15_000_000_000
                   })

          for time <- [0, 15, 30, 45, 60] do
            entries =
              for sample <- result["data"]["result"],
                  [timestamp, value] <- sample["values"],
                  timestamp == time,
                  do: %{"metric" => sample["metric"], "value" => [timestamp, value]}

            reference_case(expression, time, entries)
          end
        end
      )

    inputs =
      Enum.map_join(series, "", fn {name, fields, values} ->
        "      - series: #{quote_yaml(name <> labels(fields))}\n        values: #{quote_yaml(Enum.join(values, " "))}\n"
      end)

    directory = Path.join(System.tmp_dir!(), "pulso-prometheus-#{System.unique_integer([:positive])}")
    File.mkdir_p!(directory)
    on_exit(fn -> File.rm_rf!(directory) end)
    path = Path.join(directory, "reference.yml")

    File.write!(
      path,
      "evaluation_interval: 10s\ntests:\n  - interval: 10s\n    input_series:\n#{inputs}    promql_expr_test:\n#{Enum.join(cases ++ range_cases)}"
    )

    {output, status} = System.cmd(System.fetch_env!("PULSO_PROMTOOL"), ["test", "rules", path], stderr_to_stdout: true)
    assert status == 0, output
  end

  defp reference_case(expression, time, entries) do
    samples =
      Enum.map_join(entries, ", ", fn sample ->
        "{labels: #{quote_yaml(labels(sample["metric"]))}, value: #{Enum.at(sample["value"], 1)}}"
      end)

    "      - expr: #{quote_yaml(expression)}\n        eval_time: #{time}s\n        exp_samples: [#{samples}]\n"
  end

  defp labels(fields) do
    "{" <>
      (fields |> Enum.sort() |> Enum.map_join(",", fn {name, value} -> "#{name}=#{JSON.encode!(value)}" end)) <> "}"
  end

  defp quote_yaml(value), do: "'" <> String.replace(value, "'", "''") <> "'"
end
