{{- include "pulso.validate" . }}
{{- if not .Values.existingSecret }}
{{- $secretKeyBase := .Values.secretKeyBase }}
{{- if not $secretKeyBase }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "pulso.fullname" .) }}
{{- if and $existing $existing.data (index $existing.data "SECRET_KEY_BASE") }}
{{- $secretKeyBase = index $existing.data "SECRET_KEY_BASE" | b64dec }}
{{- else }}
{{- $secretKeyBase = randAlphaNum 64 }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulso.fullname" . }}
  labels:
    {{- include "pulso.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ $secretKeyBase | b64enc | quote }}
  PULSO_TENANT_TOKENS: {{ .Values.tenantTokens | toJson | b64enc | quote }}
  PULSO_S3_ACCESS_KEY_ID: {{ .Values.storage.accessKeyId | b64enc | quote }}
  PULSO_S3_SECRET_ACCESS_KEY: {{ .Values.storage.secretAccessKey | b64enc | quote }}
{{- end }}
